// Generated by LPG2 2.3.0; runtime ABI: lpg-rust-runtime-v1
pub struct minimalsym;

impl minimalsym {
    pub const a: i32 = 1;
    pub const EOF_TOKEN: i32 = 2;

    pub const ORDERED_TERMINAL_SYMBOLS: &[&str] = &[
        "",
        "a",
        "EOF_TOKEN",
    ];

    pub const NUM_TOKEN_KINDS: i32 = 2;

    pub const IS_VALID_FOR_PARSER: bool = true;
}
