// Generated by LPG2 2.3.0; runtime ABI: lpg-rust-runtime-v1
#[derive(Clone, Copy, Debug, Default)]
pub struct minimalprs;

impl minimalprs {
    pub fn new() -> Self {
        minimalprs
    }
}

pub const minimalprs_ERROR_SYMBOL: i32 = 0;
pub const minimalprs_SCOPE_UBOUND: i32 = 0;
pub const minimalprs_SCOPE_SIZE: i32 = 0;
pub const minimalprs_MAX_NAME_LENGTH: i32 = 0;
pub const minimalprs_NUM_STATES: i32 = 2;
pub const minimalprs_NT_OFFSET: i32 = 2;
pub const minimalprs_LA_STATE_OFFSET: i32 = 8;
pub const minimalprs_MAX_LA: i32 = 0;
pub const minimalprs_NUM_RULES: i32 = 1;
pub const minimalprs_NUM_NONTERMINALS: i32 = 2;
pub const minimalprs_NUM_SYMBOLS: i32 = 4;
pub const minimalprs_START_STATE: i32 = 2;
pub const minimalprs_IDENTIFIER_SYMBOL: i32 = 0;
pub const minimalprs_EOFT_SYMBOL: i32 = 2;
pub const minimalprs_EOLT_SYMBOL: i32 = 3;
pub const minimalprs_ACCEPT_ACTION: i32 = 6;
pub const minimalprs_ERROR_ACTION: i32 = 7;
pub const minimalprs_BACKTRACK: bool = false;
pub const minimalprs_GLR: bool = false;

static minimalprs_is_nullable: &[i32] = &[0,
            0,0,0,0,
];

static minimalprs_prostheses_index: &[i32] = &[0,
            2,1,
];

static minimalprs_is_keyword: &[i32] = &[0,
            0,0,
];

static minimalprs_base_check: &[i32] = &[0,
            1,
];
static minimalprs_rhs: &[i32] = minimalprs_base_check;


static minimalprs_base_action: &[i32] = &[
            1,1,1,4,3,7,7,
];
static minimalprs_lhs: &[i32] = minimalprs_base_action;


static minimalprs_term_check: &[i32] = &[0,
            0,1,0,0,2,
];

static minimalprs_term_action: &[i32] = &[0,
            7,8,7,7,6,
];

impl lpg2::traits::ParseTable for minimalprs {
    fn get_error_symbol(&self) -> i32 {
        minimalprs_ERROR_SYMBOL
    }
    fn get_scope_ubound(&self) -> i32 {
        minimalprs_SCOPE_UBOUND
    }
    fn get_scope_size(&self) -> i32 {
        minimalprs_SCOPE_SIZE
    }
    fn get_max_name_length(&self) -> i32 {
        minimalprs_MAX_NAME_LENGTH
    }
    fn get_num_states(&self) -> i32 {
        minimalprs_NUM_STATES
    }
    fn get_nt_offset(&self) -> i32 {
        minimalprs_NT_OFFSET
    }
    fn get_la_state_offset(&self) -> i32 {
        minimalprs_LA_STATE_OFFSET
    }
    fn get_max_la(&self) -> i32 {
        minimalprs_MAX_LA
    }
    fn get_num_rules(&self) -> i32 {
        minimalprs_NUM_RULES
    }
    fn get_num_nonterminals(&self) -> i32 {
        minimalprs_NUM_NONTERMINALS
    }
    fn get_num_symbols(&self) -> i32 {
        minimalprs_NUM_SYMBOLS
    }
    fn get_start_state(&self) -> i32 {
        minimalprs_START_STATE
    }
    fn get_eoft_symbol(&self) -> i32 {
        minimalprs_EOFT_SYMBOL
    }
    fn get_eolt_symbol(&self) -> i32 {
        minimalprs_EOLT_SYMBOL
    }
    fn get_accept_action(&self) -> i32 {
        minimalprs_ACCEPT_ACTION
    }
    fn get_error_action(&self) -> i32 {
        minimalprs_ERROR_ACTION
    }
    fn get_backtrack(&self) -> bool {
        minimalprs_BACKTRACK
    }
    fn is_glr(&self) -> bool {
        minimalprs_GLR
    }
    fn get_start_symbol(&self) -> i32 {
        self.lhs(0)
    }

    fn is_valid_for_parser(&self) -> bool {
        true
    }

    fn is_nullable(&self, symbol: i32) -> bool {
        minimalprs_is_nullable[symbol as usize] != 0
    }
    fn base_check(&self, index: i32) -> i32 {
        minimalprs_base_check[index as usize]
    }
    fn rhs(&self, index: i32) -> i32 {
        minimalprs_rhs[index as usize]
    }

    fn base_action(&self, index: i32) -> i32 {
        minimalprs_base_action[index as usize]
    }
    fn lhs(&self, index: i32) -> i32 {
        minimalprs_lhs[index as usize]
    }

    fn term_check(&self, index: i32) -> i32 {
        minimalprs_term_check[index as usize]
    }
    fn term_action(&self, index: i32) -> i32 {
        minimalprs_term_action[index as usize]
    }
    fn asb(&self, _index: i32) -> i32 { 0 }

    fn asr(&self, _index: i32) -> i32 { 0 }

    fn nasb(&self, _index: i32) -> i32 { 0 }

    fn nasr(&self, _index: i32) -> i32 { 0 }

    fn terminal_index(&self, _index: i32) -> i32 { 0 }

    fn nonterminal_index(&self, _index: i32) -> i32 { 0 }

    fn scope_prefix(&self, _index: i32) -> i32 { 0 }

    fn scope_suffix(&self, _index: i32) -> i32 { 0 }

    fn scope_lhs(&self, _index: i32) -> i32 { 0 }

    fn scope_la(&self, _index: i32) -> i32 { 0 }

    fn scope_state_set(&self, _index: i32) -> i32 { 0 }

    fn scope_rhs(&self, _index: i32) -> i32 { 0 }

    fn scope_state(&self, _index: i32) -> i32 { 0 }

    fn in_symb(&self, _index: i32) -> i32 { 0 }

    fn name(&self, _index: i32) -> String { String::new() }

    fn original_state(&self, _state: i32) -> i32 { 0 }

    fn asi(&self, _state: i32) -> i32 { 0 }

    fn nasi(&self, _state: i32) -> i32 { 0 }

    fn in_symbol(&self, _state: i32) -> i32 { 0 }

    fn nt_action(&self, state: i32, sym: i32) -> i32 {
        minimalprs_base_action[(state + sym) as usize]
    }

    fn t_action(&self, act: i32, sym: i32) -> i32 {
        let i = minimalprs_base_action[act as usize];
        let k = i + sym;
        let index = if minimalprs_term_check[k as usize] == sym { k } else { i };
        minimalprs_term_action[index as usize]
    }

    fn look_ahead(&self, la_state: i32, sym: i32) -> i32 {
        let k = la_state + sym;
        let index = if minimalprs_term_check[k as usize] == sym { k } else { la_state };
        minimalprs_term_action[index as usize]
    }

}

